### ISSUE TITLE
Add css variables for font size

### ISSUE THREAD

**Issue by hyp530** [vuepress/vuepress-next#816]
### Description

Wondering if you could provide css variables in `vars.scss' and `vars-dark.scss` for font-size -  both headers and body text.

**Comment by Mister-Hope** [comment]
I don't think this is a common case, as most website font size is all 16px.

If you really want to modify this:

`.vuepress/styles/index.scss`

```scss
body {
  font-size: 18px !important;
}
```
