### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by clark-cui** [vuepress/vuepress-next#926]
### Description

Click the item on the left sidebar.The content did not scroll into the correct position. It seemd  a little bit lower.

Visit the [vuepress-next website](https://v2.vuepress.vuejs.org/guide/deployment.html#google-firebase)  can repoduce this bug.

### Reproduction

https://v2.vuepress.vuejs.org/guide/deployment.html#google-firebase

### Used Package Manager

npm

### System Info

```shell
Chrome 102.0.5005.61
```

**Comment by clark-cui** [comment]
This can be fixed by adding a css rule.

```css
.theme-default-content:not(.custom)>h1, .theme-default-content:not(.custom)>h2, .theme-default-content:not(.custom)>h3, .theme-default-content:not(.custom)>h4, .theme-default-content:not(.custom)>h5, .theme-default-content:not(.custom)>h6 {
    margin-top: -3.1rem;
    padding-top: 4.6rem;
    margin-bottom: 0;

```

**Comment by clark-cui** [comment]
ok,I found this problem had been fixd by this code which been added before 1 year. however the website is still have this problem.It seemd this css file did not load correctly.

```scss
.theme-default-content {
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    margin-top: calc(0.5rem - var(--navbar-height));
    padding-top: calc(1rem + var(--navbar-height));
    margin-bottom: 0;
  }
}

```
